# The Purpose of this workflow file is to enable us to automatically
# synchronize the staging repository with the latest commit
# of CATcher-org/WATcher.

name: Fetch Upstream Master to Staging

on:
  push:
    branches: [master]

jobs:
  fetch_from_upstream:
    if: ${{ github.repository == 'MadLamprey/WATcher' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Upstream
        uses: actions/checkout@v2
        with:
          ref: deploy
          token: ${{ secrets.DEPLOY_TOKEN }}
          fetch-depth: 0
      - name: Merge Upstream
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/MadLamprey/WATcher.git 
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories
          git push origin master -f
